"""Owner-configured existing checks, bounded by the investigation deadline."""
import os
import signal
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path

from ai_maintenance.include.task.runtime import git, require_run, utcnow, write_json


def validate_base(config, run):
    """Verify immutable input in a fresh checkout, never proposed review changes."""
    if not require_run(config, run) or not config.get('validation_commands'):
        return
    with tempfile.TemporaryDirectory(prefix='ai-base-validation-') as temporary:
        checkout = str(Path(temporary) / 'checkout')
        git(config['repository'], 'worktree', 'add', '--detach', checkout, run['base_commit'])
        try:
            _validate_checkout(config, run, checkout)
        finally:
            git(config['repository'], 'worktree', 'remove', '--force', checkout)


def _validate_checkout(config, run, checkout):
    if not require_run(config, run) or not config.get('validation_commands'):
        return
    from ai_maintenance.include.task.run_agent import _redact
    results = {}
    for check in config['validation_commands']:
        remaining = (datetime.fromisoformat(run['soft_deadline']) - utcnow()).total_seconds()
        if remaining <= 0:
            write_json(Path(run['state_dir']) / 'validation_handoff.json', {'status': 'deferred'})
            break
        # Commands are owner configuration, never generated by agents. Do not pass credentials.
        env = {k: v for k, v in os.environ.items() if k in ('PATH', 'HOME', 'LANG', 'TMPDIR')}
        with tempfile.TemporaryFile() as output:
            process = subprocess.Popen(check['argv'], cwd=checkout, env=env,
                                       stdout=output, stderr=subprocess.STDOUT, start_new_session=True)
            timed_out = False
            try:
                process.wait(timeout=min(remaining, check.get('timeout_seconds', 120)))
            except subprocess.TimeoutExpired:
                timed_out = True
            finally:
                # Also stop background descendants of completed check processes.
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                process.wait()
            output.seek(0)
            evidence = _redact(output.read(120000).decode(errors='replace'), config)
        results[check['id']] = {'passed': process.returncode == 0 and not timed_out,
                                'timed_out': timed_out, 'evidence': evidence,
                                'argv': check['argv']}
        write_json(Path(run['state_dir']) / 'validation.json', results)
    # Checks modifying tracked content invalidate base verification.
    clean = (not git(checkout, 'status', '--porcelain', '--untracked-files=no')
             and git(checkout, 'rev-parse', 'HEAD') == run['base_commit'])
    issues = {}
    for identity, enrollment in config['linear'].get('enrolled_issues', {}).items():
        criteria = []
        for criterion, check_id in enrollment.get('verification_checks', {}).items():
            result = results.get(check_id, {})
            criteria.append({'criterion': criterion, 'verified': clean and result.get('passed') is True,
                             'evidence': 'Configured check ' + check_id + ': ' + result.get('evidence', '')})
        regression_check = results.get(enrollment.get('regression_check'), {})
        issues[identity] = {'criteria': criteria,
                            'regression_verified': clean and regression_check.get('passed') is True,
                            'regression_evidence': regression_check.get('evidence', '')}
    write_json(Path(run['state_dir']) / 'base_verification.json', {'base_commit': run['base_commit'], 'issues': issues})
    if not clean:
        raise ValueError('Configured validation modified tracked base files; review required')
